character_weapon_type_map = {
    'Albedo': 'sword',
    'Aloy': 'bow',
    'Amber': 'bow',
    'AratakiItto': 'claymore',
    'Barbara': 'catalyst',
    'Beidou': 'claymore',
    'Bennett': 'sword',
    'Chongyun': 'claymore',
    'Diluc': 'claymore',
    'Diona': 'bow',
    'Eula': 'claymore',
    'Fischl': 'bow',
    'Ganyu': 'bow',
    'Gorou': 'bow',
    'HuTao': 'polearm',
    'Jean': 'sword',
    'KaedeharaKazuha': 'sword',
    'Kaeya': 'sword',
    'KamisatoAyaka': 'sword',
    'KamisatoAyato': 'sword',
    'Keqing': 'sword',
    'Klee': 'catalyst',
    'KujouSara': 'bow',
    'Lisa': 'catalyst',
    'Mona': 'catalyst',
    'Ningguang': 'catalyst',
    'Noelle': 'claymore',
    'Qiqi': 'sword',
    'RaidenShogun': 'polearm',
    'Razor': 'claymore',
    'Rosaria': 'polearm',
    'SangonomiyaKokomi': 'catalyst',
    'Sayu': 'claymore',
    'Shenhe': 'polearm',
    'Sucrose': 'catalyst',
    'Tartaglia': 'bow',
    'Thoma': 'polearm',
    'Traveler': 'sword',
    'Venti': 'bow',
    'Xiangling': 'polearm',
    'Xiao': 'polearm',
    'Xingqiu': 'sword',
    'Xinyan': 'claymore',
    'Yanfei': 'catalyst',
    'YaeMiko': 'catalyst',
    'Yelan': 'bow',
    'Yunjin': 'polearm',
    'Yoimiya': 'bow',
    'Zhongli': 'polearm',
}

character_element_map = {
    'Albedo': 'geo',
    'Aloy': 'cryo',
    'Amber': 'pyro',
    'AratakiItto': 'geo',
    'Barbara': 'hydro',
    'Beidou': 'electro',
    'Bennett': 'pyro',
    'Chongyun': 'cryo',
    'Diluc': 'pyro',
    'Diona': 'cryo',
    'Eula': 'cryo',
    'Fischl': 'electro',
    'Ganyu': 'cryo',
    'Gorou': 'geo',
    'HuTao': 'pyro',
    'Jean': 'anemo',
    'KaedeharaKazuha': 'anemo',
    'Kaeya': 'cryo',
    'KamisatoAyaka': 'cryo',
    'KamisatoAyato': 'hydro',
    'Keqing': 'electro',
    'Klee': 'pyro',
    'KujouSara': 'electro',
    'Lisa': 'electro',
    'Mona': 'hydro',
    'Ningguang': 'geo',
    'Noelle': 'geo',
    'Qiqi': 'cryo',
    'RaidenShogun': 'electro',
    'Razor': 'electro',
    'Rosaria': 'cryo',
    'SangonomiyaKokomi': 'hydro',
    'Sayu': 'anemo',
    'Shenhe': 'cryo',
    'Sucrose': 'anemo',
    'Tartaglia': 'hydro',
    'Thoma': 'pyro',
    'Traveler': 'anemo',  # Good doesn't differentiate the travelers. Use 'anemo' as default
    'Venti': 'anemo',
    'Xiangling': 'pyro',
    'Xiao': 'anemo',
    'Xingqiu': 'hydro',
    'Xinyan': 'pyro',
    'Yanfei': 'pyro',
    'YaeMiko': 'electro',
    'Yelan': 'hydro',
    'Yunjin': 'geo',
    'Yoimiya': 'pyro',
    'Zhongli': 'geo',
}

good_to_gcsim_character = {key: key.lower() for key in character_weapon_type_map.keys()}
gcsim_to_good_character = {value: key for key, value in good_to_gcsim_character.items()}

# TODO(andre): export a function from gcsim into the shared library to convert GOOD character into gcsim charkey
#  to make sure the conversion it's updated
gcsim_charkey_to_string = [
    'NoChar',
    'TravelerElectro',
    'TravelerAnemo',
    'TravelerGeo',
    'TravelerHydro',
    'TravelerCryo',
    'TravelerPyro',
    'TravelerDendro',
    'Traveler',  # Good doesn't differentiate the travelers. Use 'TravelerMale' as default
    'TravelerFemale',
    'TravelerDelim',
    'Albedo',
    'Aloy',
    'Amber',
    'Barbara',
    'Beidou',
    'Bennett',
    'Chongyun',
    'Diluc',
    'Diona',
    'Eula',
    'Fischl',
    'Ganyu',
    'HuTao',
    'Jean',
    'KaedeharaKazuha',
    'Kaeya',
    'KamisatoAyaka',
    'KamisatoAyato',
    'Keqing',
    'Klee',
    'KujouSara',
    'Lisa',
    'Mona',
    'Ningguang',
    'Noelle',
    'Qiqi',
    'RaidenShogun',
    'Razor',
    'Rosaria',
    'SangonomiyaKokomi',
    'Sayu',
    'Sucrose',
    'Tartaglia',
    'Thoma',
    'Venti',
    'Xiangling',
    'Xiao',
    'Xingqiu',
    'Xinyan',
    'Yanfei',
    'Yoimiya',
    'Zhongli',
    'Gorou',
    'AratakiItto',
    'Shenhe',
    'Yunjin',
    'YaeMiko',
    'Yelan',
]
string_to_gcsim_charkey = {key: i for i, key in enumerate(gcsim_charkey_to_string)}
